fields:
  anchorHeadline:
    type: headline
    label: Navigation
    numbered: false
  anchor:
    label: ID
    type: text
    help: "Wird fÃ¼r die Navigation benÃ¶tigt."
  backgroundHeadline:
    type: headline
    label: Hintergrund
    numbered: false
  backgroundContainer:
    label: Breite
    type: toggles
    default: container
    width: 2/4
    options:
      container: Container
      w-full: Volle Breite
  backgroundHeight:
    label: HÃ¶he
    type: select
    width: 1/4
    default: auto
    options:
      full: Vollbild
      half: Halber Bildschirm
      auto: Automatisch
  backgroundAlign:
    width: 1/4
    label: Ausrichtung
    extends: fields/align
  backgroundContainerColor:
    label: Farbe Container
    type: select
    default: transparent
    width: 1/4
    extends: fields/colors
  backgroundColor:
    type: select
    label: Farbe Hintergrund
    default: transparent
    width: 1/4
    extends: fields/colors
  spacingHeadline:
    type: headline
    label: AbstÃ¤nde
    numbered: false
  spacingMobileTop:
    label: â¬†ï¸ ğŸ“±
    extends: fields/spacing
  spacingMobileBottom:
    label: â¬‡ï¸ ğŸ“±
    extends: fields/spacing
  spacingDesktopTop:
    label: â¬†ï¸ ğŸ–¥ï¸
    extends: fields/spacing
  spacingDesktopBottom:
    label: â¬‡ï¸ ğŸ–¥ï¸
    extends: fields/spacing
