fields:
  backgroundHeadline:
    type: headline
    label: Hintergrund
    numbered: false
  backgroundContainer:
    label: Breite
    type: toggles
    default: container
    width: 1/2
    options:
      container: Container
      w-full: Volle Breite
  backgroundColor:
    type: select
    label: Farbe
    default: transparent
    width: 1/2
    extends: fields/colors
  spacingHeadline:
    type: headline
    label: AbstÃ¤nde
    numbered: false
  spacingMobileTop:
    label: â¬†ï¸ ğŸ“±
    type: number
    default: 0
    after: px
    width: 1/4
  spacingMobileBottom:
    label: â¬‡ï¸ ğŸ“±
    type: number
    default: 0
    after: px
    width: 1/4
  spacingDesktopTop:
    label: â¬†ï¸ ğŸ–¥ï¸
    type: number
    default: 0
    after: px
    width: 1/4
  spacingDesktopBottom:
    label: â¬‡ï¸ ğŸ–¥ï¸
    type: number
    after: px
    default: 0
    width: 1/4
